# Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr)
print("array slicing:\n",arr[2:7])
print("with step:\n",arr[1:8:2])
print("Negative indexing:\n",arr[-6])


Array:
 [ 1  2  3  4  5  6  7  8  9 10]
array slicing:
 [3 4 5 6 7]
with step:
 [2 4 6 8]
Negative indexing:
 5


In [7]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Array:\n",arr_2d)
print("Specific element: ",arr_2d[2,2])
print("Entire row: ",arr_2d[2])
print("Entire coloumn: ",arr_2d[:,2])

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  9
Entire row:  [7 8 9]
Entire coloumn:  [3 6 9]


## Sorting

In [ ]:
unsorted = np.array([1,5,6,2,4,2,1,9,0,2])
print("Sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2-D array:\n",np.sort(arr_2d_unsorted, axis=0))
# axis = 0 means sorted top to bottom
# axis = 1 means sorted row wise

Sorted array:  [0 1 1 2 2 2 4 5 6 9]
Sorted 2-D array:
 [[1 1]
 [2 2]
 [3 3]]


## Filter

In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,0])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ",even_numbers)

Even numbers:  [2 4 6 8 0]


## Filter with mask

In [14]:
mask = numbers > 5
print("Numbers greater than 5 ",numbers[mask])

Numbers greater than 5  [6 7 8 9]


## Fancy indexing vs np.where()

In [18]:
indices = [1,3,5]
print(numbers[indices])

where_result = np.where(numbers>5)
print("Np where :",numbers[where_result])

[2 4 6]
Np where : [6 7 8 9]


In [28]:
condition_array = np.where(numbers > 5 , numbers*4 , numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36  0]


## Combine two array

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined_array = np.concatenate((arr1,arr2))
print("Combined:",combined_array)

Combined: [1 2 3 4 5 6]


### Array compatibility

In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6,8])
c = np.array([7,8,9])

print("Compatibility shapes :",a.shape == b.shape)

Compatibility shapes : False


### Delete element

In [32]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3)
print("After deletion:",deleted)
deleted_1 =np.delete(arr,2)
print("After deletion:",deleted_1)

After deletion: [1 2 3 5]
After deletion: [1 2 4 5]


### Adding new row and col

In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
# add row
new_row = np.array([1,7,0])
final_arr = np.vstack((arr_2d,new_row))
print("Final:\n",final_arr)
# add col
new_col= np.array([[2],[3],[7]])
final_arr_1 = np.hstack((arr_2d,new_col))
print("Final:\n",final_arr_1)


Final:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 7 0]]
Final:
 [[1 2 3 2]
 [4 5 6 3]
 [7 8 9 7]]
