## Numpy array and basics

### learn about numpy

In [2]:
import numpy as np

In [6]:
arr_1 = np.array([1,2,3])
print(arr_1)
print(arr_1*2)

list_1 = [1,2,3]
print(list_1)
print(list_1*2)

[1 2 3]
[2 4 6]
[1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [ ]:
import time

start = time.time()
py_list = [i*2 for  i in range(100000)]
print("list operation time: ",time.time() - start)

start = time.time()
py_array = np.arange(100000) * 2
print("array operation time: ",time.time() - start)

list operation time:  0.006793975830078125
array operation time:  0.002853870391845703


### creating array from scratch

In [15]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

ones = np.ones((4,4))
print("ones array:\n",ones)

full = np.full((2,2),5)
print("full array:\n",full)

random = np.random.random((2,3))
print("random array:\n",random)
# random always returns value between 0 and 1

sequence = np.arange(0, 10, 2)
print("sequence array: ",sequence)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[5 5]
 [5 5]]
random array:
 [[0.42570491 0.43238286 0.74443382]
 [0.83746255 0.77908026 0.82128928]]
sequence array:  [0 2 4 6 8]


### Vector, Matrices and Tensor

In [20]:
vector = np.array([1,2,3])
print("vector: ",vector)

matrices = np.array([[1,2,3],
                     [4,5,6]])
print("Matrices:\n",matrices)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:\n",tensor)

vector:  [1 2 3]
Matrices:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [22]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Data Type: ",arr.dtype)

# we can store multiple data types but we store similar type data types in a array.

Shape: (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


### Array reshaping

In [30]:
arr = np.arange(12)
print("Original array:\n",arr)
#reshaping property
reshaped = arr.reshape((3,4))
print("\nReshaped Array:\n",reshaped)
#flatten property
flattened = reshaped.flatten()
print("\nflattened array:\n",flattened)
#ravel property(return view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled array:\n",raveled)
#transpose
transposed = reshaped.T
print("\nTransposed array:\n",transposed)



Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
